// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/aljrubior/standalone-runtime/clients/serverClient/defaultServerClient"
	"github.com/aljrubior/standalone-runtime/conf"
	"github.com/aljrubior/standalone-runtime/managers/serverManager"
	"github.com/aljrubior/standalone-runtime/services"
)

// Injectors from serverManagerWire.go:

func InitializeAccountManager(config conf.ServerClientConfig) serverManager.ServerManager {
	defaultServerClientDefaultServerClient := defaultServerClient.NewDefaultServerClient(config)
	defaultServerService := services.NewDefaultServerService(defaultServerClientDefaultServerClient)
	defaultServerManager := serverManager.NewDefaultServerManager(defaultServerService)
	return defaultServerManager
}
