// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/aljrubior/standalone-runtime/clients/serverClient"
	"github.com/aljrubior/standalone-runtime/conf"
	"github.com/aljrubior/standalone-runtime/managers/serverManager"
	"github.com/aljrubior/standalone-runtime/managers/serverRegistrationManager"
	"github.com/aljrubior/standalone-runtime/services"
)

// Injectors from serverManagerWire.go:

func InitializeServerManager(config conf.ServerClientConfig) serverManager.ServerManager {
	defaultServerClientDefaultServerClient := serverClient.NewDefaultServerClient(config)
	defaultServerService := services.NewDefaultServerService(defaultServerClientDefaultServerClient)
	defaultServerManager := serverManager.NewDefaultServerManager(defaultServerService)
	return defaultServerManager
}

// Injectors from serverRegistrationManager.go:

func InitializeServerRegistrationManager(csrConfig conf.CSRConfig, serverManager2 serverManager.ServerManager) serverRegistrationManager.ServerRegistrationManager {
	defaultServerRegistrationManager := serverRegistrationManager.NewDefaultServerRegistrationManager(serverManager2, csrConfig)
	return defaultServerRegistrationManager
}
